// ── Lecturer profile ──────────────────────────────────────────────────────────
export const LECTURER = {
  name: 'Dr. Sarath Gunasekara',
  initials: 'SG',
  title: 'Senior Lecturer',
  department: 'Faculty of Computing',
  employeeId: 'LEC-2018-001',
  subjects: ['Database Design and Development (IT2140)', 'Web and Mobile Technologies (SE2020)'],
  stats: {
    downloads: 342,
    pendingReviews: 7,
    uploadedResources: 24,
    myPoints: 180,
  },
};

// ── Subjects this lecturer teaches ────────────────────────────────────────────
export const SUBJECTS = [
  'Probability and Statistics (IT2120)',
  'Object Oriented Programming (SE2010)',
  'Operating Systems & System Administration (IT2130)',
  'Database Design and Development (IT2140)',
  'Artificial Intelligence & Machine Learning (IT2011)',
  'IT Project (IT2150)',
  'Web and Mobile Technologies (SE2020)',
  'Professional Skills (IT2160)',
];

// ── Student-uploaded notes pending review ─────────────────────────────────────
export const PENDING_RESOURCES = [
  {
    id: 1,
    studentName: 'Kavindu Perera',
    studentInitials: 'KP',
    studentRank: 1,
    studentLikes: 142,
    title: 'OOP Concepts Notes',
    subject: 'Object Oriented Programming (SE2010)',
    file: 'OOP_Concepts_Notes.pdf',
    fileSize: '1.2 MB',
    uploadedAt: '2026-02-17T13:10:00',
    status: 'pending',
    rejectionNote: '',
  },
  {
    id: 2,
    studentName: 'Dilini Senanayake',
    studentInitials: 'DS',
    studentRank: 4,
    studentLikes: 87,
    title: 'Java Cheat Sheet',
    subject: 'Object Oriented Programming (SE2010)',
    file: 'Java_Cheat_Sheet.pdf',
    fileSize: '0.8 MB',
    uploadedAt: '2026-02-18T11:00:00',
    status: 'pending',
    rejectionNote: '',
  },
  {
    id: 3,
    studentName: 'Pathum Dhananjaya',
    studentInitials: 'PD',
    studentRank: 2,
    studentLikes: 115,
    title: 'SQL Cheat Sheet',
    subject: 'Database Design and Development (IT2140)',
    file: 'SQL_Cheat_Sheet.pdf',
    fileSize: '0.5 MB',
    uploadedAt: '2026-02-19T08:20:00',
    status: 'pending',
    rejectionNote: '',
  },
  {
    id: 4,
    studentName: 'Tharushi Fernando',
    studentInitials: 'TF',
    studentRank: 3,
    studentLikes: 98,
    title: 'React Summary',
    subject: 'Web and Mobile Technologies (SE2020)',
    file: 'React_Summary.pdf',
    fileSize: '2.1 MB',
    uploadedAt: '2026-02-20T09:15:00',
    status: 'pending',
    rejectionNote: '',
  },
  {
    id: 5,
    studentName: 'Isuru Herath',
    studentInitials: 'IH',
    studentRank: 7,
    studentLikes: 54,
    title: 'ML Basics Summary',
    subject: 'Artificial Intelligence & Machine Learning (IT2011)',
    file: 'ML_Basics_Summary.pdf',
    fileSize: '1.5 MB',
    uploadedAt: '2026-02-21T14:30:00',
    status: 'pending',
    rejectionNote: '',
  },
  {
    id: 6,
    studentName: 'Kavindu Perera',
    studentInitials: 'KP',
    studentRank: 5,
    studentLikes: 76,
    title: 'Neural Networks Notes',
    subject: 'Artificial Intelligence & Machine Learning (IT2011)',
    file: 'Neural_Networks_Notes.pdf',
    fileSize: '3.2 MB',
    uploadedAt: '2026-02-22T16:45:00',
    status: 'pending',
    rejectionNote: '',
  },
  {
    id: 7,
    studentName: 'Dilini Senanayake',
    studentInitials: 'DS',
    studentRank: 6,
    studentLikes: 65,
    title: 'ER Diagram Examples',
    subject: 'Database Design and Development (IT2140)',
    file: 'ER_Diagrams.pdf',
    fileSize: '1.8 MB',
    uploadedAt: '2026-02-23T10:00:00',
    status: 'pending',
    rejectionNote: '',
  },
];

// ── Quizzes already created ───────────────────────────────────────────────────
export const INITIAL_QUIZZES = [
  {
    id: 1,
    title: 'ML Basics Quiz',
    subject: 'Artificial Intelligence & Machine Learning (IT2011)',
    questionCount: 5,
    attempts: 34,
    createdAt: '2026-02-10',
    questions: [
      { id: 1, question: 'What does supervised learning use to train a model?', options: ['Unlabeled data', 'Labeled data', 'Random data', 'No data'], answer: 1 },
      { id: 2, question: 'Which of these is a classification algorithm?',       options: ['K-Means', 'Linear Regression', 'Decision Tree', 'PCA'],          answer: 2 },
    ],
  },
  {
    id: 2,
    title: 'OOP Quiz',
    subject: 'Object Oriented Programming (SE2010)',
    questionCount: 8,
    attempts: 28,
    createdAt: '2026-02-14',
    questions: [
      { id: 1, question: 'What is encapsulation?', options: ['Hiding implementation details', 'Creating new classes', 'Inheriting from parent', 'Runtime polymorphism'], answer: 0 },
    ],
  },
];