// // ── Lecturer profile ──────────────────────────────────────────────────────────
// export const LECTURER = {
//   name: 'Dr. Emily Chen',
//   initials: 'EC',
//   title: 'Senior Lecturer',
//   department: 'Faculty of Engineering',
//   employeeId: 'LEC-2018-045',
//   subjects: ['Database Management Systems', 'Advanced Algorithms'],
//   stats: {
//     downloads: 342,
//     pendingReviews: 7,
//     uploadedResources: 24,
//     myPoints: 180,
//   },
// };

// // ── Subjects this lecturer teaches ────────────────────────────────────────────
// export const SUBJECTS = [
//   'Introduction to Machine Learning',
//   'Data Structures and Algorithms',
//   'Database Management Systems',
//   'Advanced Algorithms',
// ];

// // ── Student-uploaded notes pending review ─────────────────────────────────────
// export const PENDING_RESOURCES = [
//   {
//     id: 1,
//     studentName: 'Sarah Williams',
//     studentInitials: 'SW',
//     studentRank: 1,
//     studentLikes: 142,
//     title: 'Tree Traversal Notes',
//     subject: 'Data Structures and Algorithms',
//     file: 'Tree_Traversal_Notes.pdf',
//     fileSize: '1.2 MB',
//     uploadedAt: '2026-02-17T13:10:00',
//     status: 'pending',
//     rejectionNote: '',
//   },
//   {
//     id: 2,
//     studentName: 'Tom Brown',
//     studentInitials: 'TB',
//     studentRank: 4,
//     studentLikes: 87,
//     title: 'Sorting Algorithms Cheat Sheet',
//     subject: 'Data Structures and Algorithms',
//     file: 'Sorting_Cheat_Sheet.pdf',
//     fileSize: '0.8 MB',
//     uploadedAt: '2026-02-18T11:00:00',
//     status: 'pending',
//     rejectionNote: '',
//   },
//   {
//     id: 3,
//     studentName: 'Mike Johnson',
//     studentInitials: 'MJ',
//     studentRank: 2,
//     studentLikes: 115,
//     title: 'SQL Cheat Sheet',
//     subject: 'Database Management Systems',
//     file: 'SQL_Cheat_Sheet.pdf',
//     fileSize: '0.5 MB',
//     uploadedAt: '2026-02-19T08:20:00',
//     status: 'pending',
//     rejectionNote: '',
//   },
//   {
//     id: 4,
//     studentName: 'Emily Davis',
//     studentInitials: 'ED',
//     studentRank: 3,
//     studentLikes: 98,
//     title: 'Graph Theory Summary',
//     subject: 'Advanced Algorithms',
//     file: 'Graph_Theory_Summary.pdf',
//     fileSize: '2.1 MB',
//     uploadedAt: '2026-02-20T09:15:00',
//     status: 'pending',
//     rejectionNote: '',
//   },
//   {
//     id: 5,
//     studentName: 'James Wilson',
//     studentInitials: 'JW',
//     studentRank: 7,
//     studentLikes: 54,
//     title: 'ML Basics Summary',
//     subject: 'Introduction to Machine Learning',
//     file: 'ML_Basics_Summary.pdf',
//     fileSize: '1.5 MB',
//     uploadedAt: '2026-02-21T14:30:00',
//     status: 'pending',
//     rejectionNote: '',
//   },
//   {
//     id: 6,
//     studentName: 'Priya Patel',
//     studentInitials: 'PP',
//     studentRank: 5,
//     studentLikes: 76,
//     title: 'Neural Networks Notes',
//     subject: 'Introduction to Machine Learning',
//     file: 'Neural_Networks_Notes.pdf',
//     fileSize: '3.2 MB',
//     uploadedAt: '2026-02-22T16:45:00',
//     status: 'pending',
//     rejectionNote: '',
//   },
//   {
//     id: 7,
//     studentName: 'Alex Johnson',
//     studentInitials: 'AJ',
//     studentRank: 6,
//     studentLikes: 65,
//     title: 'ER Diagram Examples',
//     subject: 'Database Management Systems',
//     file: 'ER_Diagrams.pdf',
//     fileSize: '1.8 MB',
//     uploadedAt: '2026-02-23T10:00:00',
//     status: 'pending',
//     rejectionNote: '',
//   },
// ];

// // ── Quizzes already created ───────────────────────────────────────────────────
// export const INITIAL_QUIZZES = [
//   {
//     id: 1,
//     title: 'ML Basics Quiz',
//     subject: 'Introduction to Machine Learning',
//     questionCount: 5,
//     attempts: 34,
//     createdAt: '2026-02-10',
//     questions: [
//       { id: 1, question: 'What does supervised learning use to train a model?', options: ['Unlabeled data', 'Labeled data', 'Random data', 'No data'], answer: 1 },
//       { id: 2, question: 'Which of these is a classification algorithm?',       options: ['K-Means', 'Linear Regression', 'Decision Tree', 'PCA'],          answer: 2 },
//     ],
//   },
//   {
//     id: 2,
//     title: 'Data Structures Quiz',
//     subject: 'Data Structures and Algorithms',
//     questionCount: 8,
//     attempts: 28,
//     createdAt: '2026-02-14',
//     questions: [
//       { id: 1, question: 'What is the time complexity of binary search?', options: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'], answer: 1 },
//     ],
//   },
// ];